# Generated by Django 5.2.1 on 2025-05-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
