# Generated by Django 5.2.1 on 2025-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
