# Generated by Django 5.2 on 2025-05-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_rename_csid_sub_category_scategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='scategory',
            new_name='sub_category',
        ),
    ]
