# Generated by Django 5.2 on 2025-05-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_rename_scategory_sub_category_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_category',
            new_name='scategory',
        ),
    ]
