# Generated by Django 5.2 on 2025-05-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
    ]
