# Generated by Django 5.2 on 2025-06-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
