# Generated by Django 5.2 on 2025-06-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0021_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
