# Generated by Django 5.2 on 2025-06-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_review_reviewer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
