# Generated by Django 5.2 on 2025-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_user_first_name_user_last_name_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
